import { Router, type IRouter } from "express";
import healthRouter from "./health";
import replRouter from "./repl";
import snippetsRouter from "./snippets";
import playerRouter from "./player";
import suiteRouter from "./suite";
import adminRouter from "./admin";
import birthdayCalendarRouter from "./birthdayCalendar";
import gameRouter from "./game";
import filesRouter from "./files";
import zombrainsRouter from "./zombrains";
import zombrainsPersistRouter from "./zombrains-persist";
import zombrainsProposalsRouter from "./zombrains-proposals";
import zombrainsWorkersRouter from "./zombrains-workers";
import zombrainsQualityRouter from "./zombrains-quality";
import zombrainsFilesRouter from "./zombrains-files";
import zombrainsMediaRouter from "./zombrains-media";
import userRouter from "./user";
import agentRouter from "./agent";
import aiProxyRouter from "./aiProxy";
import birthdayBotRouter from "./birthdayBot";
import devLogsRouter from "./devLogs";
import zombeefRouter from "./zombeef";
import crystallineRouter from "./crystalline";
import zombrainsCloneRouter from "./zombrains-clone";
import zombrainsCrystalsRouter from "./zombrains-crystals";
import billingRouter from "./billing";

const router: IRouter = Router();

router.use(healthRouter);
router.use(replRouter);
router.use(snippetsRouter);
router.use(playerRouter);
router.use(suiteRouter);
router.use(adminRouter);
router.use(birthdayCalendarRouter);
router.use(gameRouter);
router.use(filesRouter);
router.use(zombrainsRouter);
router.use(zombrainsPersistRouter);
router.use(zombrainsProposalsRouter);
router.use(zombrainsWorkersRouter);
router.use(zombrainsQualityRouter);
router.use(zombrainsFilesRouter);
router.use(zombrainsMediaRouter);
router.use(userRouter);
router.use(agentRouter);
router.use(aiProxyRouter);
router.use(birthdayBotRouter);
router.use(devLogsRouter);
router.use(zombeefRouter);
router.use(crystallineRouter);
router.use(zombrainsCloneRouter);
router.use(zombrainsCrystalsRouter);
router.use(billingRouter);

export default router;
