export interface ShipClass {
  key: string;
  name: string;
  emoji: string;
  colour: string;
  lore: string;
  archetype: string;
  nuggetBonus: number;
  hullBonus: number;
  combatBonus: number;
  crewCapBonus: number;
  startingBonus: string;
}

export const SHIP_CLASSES: ShipClass[] = [
  {
    key: "brown_dreadnought",
    name: "Brown Dreadnought",
    emoji: "💩",
    colour: "#8B4513",
    lore: "A scarred titan of the turdbelt, feared across seven stool systems.",
    archetype: "Brawler",
    nuggetBonus: 50,
    hullBonus: 10,
    combatBonus: 15,
    crewCapBonus: 0,
    startingBonus: "+50💎 Nuggets · +10 Hull · +15⚔️ Combat",
  },
  {
    key: "methane_harvester",
    name: "Methane Harvester",
    emoji: "⛽",
    colour: "#ff7700",
    lore: "Built for one thing: extracting maximum Nuggets from the void.",
    archetype: "Harvester",
    nuggetBonus: 150,
    hullBonus: 0,
    combatBonus: 0,
    crewCapBonus: 0,
    startingBonus: "+150💎 Nuggets",
  },
  {
    key: "sphincter_fortress",
    name: "Sphincter Fortress",
    emoji: "🛡️",
    colour: "#4499ff",
    lore: "Rings of sphincter-alloy plating make this ship nearly indestructible.",
    archetype: "Tank",
    nuggetBonus: 0,
    hullBonus: 50,
    combatBonus: 0,
    crewCapBonus: 0,
    startingBonus: "+50 Hull",
  },
  {
    key: "crew_carrier",
    name: "Crew Carrier",
    emoji: "👥",
    colour: "#22cc66",
    lore: "Cavernous skid-bunks allow this ship to transport entire poo-armies.",
    archetype: "Support",
    nuggetBonus: 75,
    hullBonus: 20,
    combatBonus: 0,
    crewCapBonus: 3,
    startingBonus: "+75💎 Nuggets · +20 Hull · +3👾 Crew Cap",
  },
  {
    key: "stool_frigate",
    name: "Stool Frigate",
    emoji: "🚀",
    colour: "#D39A45",
    lore: "The workhorse of the poo-fleet. Equally deadly and profitable.",
    archetype: "Balanced",
    nuggetBonus: 50,
    hullBonus: 20,
    combatBonus: 5,
    crewCapBonus: 1,
    startingBonus: "+50💎 · +20 Hull · +5⚔️ Combat · +1👾 Crew Cap",
  },
  {
    key: "nugget_galleon",
    name: "Nugget Galleon",
    emoji: "💰",
    colour: "#ffaa00",
    lore: "Merchants' dream. Its reinforced cargo holds drip with liquid Nuggets.",
    archetype: "Harvester",
    nuggetBonus: 200,
    hullBonus: 0,
    combatBonus: 0,
    crewCapBonus: 0,
    startingBonus: "+200💎 Nuggets",
  },
  {
    key: "turd_destroyer",
    name: "Turd Destroyer",
    emoji: "💥",
    colour: "#ff2244",
    lore: "Stripped of everything non-lethal. Pure compressed aggression.",
    archetype: "Brawler",
    nuggetBonus: 25,
    hullBonus: 5,
    combatBonus: 25,
    crewCapBonus: 0,
    startingBonus: "+25💎 Nuggets · +5 Hull · +25⚔️ Combat",
  },
  {
    key: "poo_corvette",
    name: "Poo Corvette",
    emoji: "🌊",
    colour: "#00ccdd",
    lore: "Swift and nimble. Slips between enemy formations like a greased nugget.",
    archetype: "Scout",
    nuggetBonus: 80,
    hullBonus: 15,
    combatBonus: 5,
    crewCapBonus: 1,
    startingBonus: "+80💎 Nuggets · +15 Hull · +5⚔️ Combat · +1👾 Crew Cap",
  },
  {
    key: "fecal_flagship",
    name: "Fecal Flagship",
    emoji: "👑",
    colour: "#aa44ff",
    lore: "Every fleet has one. Reeking of authority and expensive poo-plating.",
    archetype: "Command",
    nuggetBonus: 75,
    hullBonus: 30,
    combatBonus: 10,
    crewCapBonus: 1,
    startingBonus: "+75💎 Nuggets · +30 Hull · +10⚔️ Combat · +1👾 Crew Cap",
  },
  {
    key: "skid_scout",
    name: "Skid Scout",
    emoji: "🔭",
    colour: "#00aa88",
    lore: "Designed to reach the outer ring of the turd nebula and report back.",
    archetype: "Scout",
    nuggetBonus: 100,
    hullBonus: 10,
    combatBonus: 0,
    crewCapBonus: 2,
    startingBonus: "+100💎 Nuggets · +10 Hull · +2👾 Crew Cap",
  },
  {
    key: "brown_hole_cruiser",
    name: "Brown Hole Cruiser",
    emoji: "🌀",
    colour: "#5566ff",
    lore: "Engineered near a brown dwarf. Gravitational poo-fields warp reality.",
    archetype: "Tank",
    nuggetBonus: 50,
    hullBonus: 40,
    combatBonus: 0,
    crewCapBonus: 0,
    startingBonus: "+50💎 Nuggets · +40 Hull",
  },
  {
    key: "nugget_nova",
    name: "Nugget Nova",
    emoji: "⭐",
    colour: "#aacc00",
    lore: "Goes supernova in profitability. Every sector visit floods the holds.",
    archetype: "Harvester",
    nuggetBonus: 120,
    hullBonus: 10,
    combatBonus: 0,
    crewCapBonus: 0,
    startingBonus: "+120💎 Nuggets · +10 Hull",
  },
  {
    key: "plop_phantom",
    name: "Plop Phantom",
    emoji: "👻",
    colour: "#8866cc",
    lore: "Sensors can't detect it. It arrives silently and leaves richer.",
    archetype: "Stealth",
    nuggetBonus: 100,
    hullBonus: 20,
    combatBonus: 8,
    crewCapBonus: 0,
    startingBonus: "+100💎 Nuggets · +20 Hull · +8⚔️ Combat",
  },
  {
    key: "sewage_serpent",
    name: "Sewage Serpent",
    emoji: "🐍",
    colour: "#00bb66",
    lore: "Long and armoured, it slithers through asteroid fields unscathed.",
    archetype: "Tank",
    nuggetBonus: 25,
    hullBonus: 60,
    combatBonus: 0,
    crewCapBonus: 0,
    startingBonus: "+25💎 Nuggets · +60 Hull",
  },
  {
    key: "methane_marauder",
    name: "Methane Marauder",
    emoji: "🏴‍☠️",
    colour: "#ff5500",
    lore: "A notorious pirate vessel. Steals Nuggets, then burns the evidence.",
    archetype: "Brawler",
    nuggetBonus: 100,
    hullBonus: 10,
    combatBonus: 15,
    crewCapBonus: 0,
    startingBonus: "+100💎 Nuggets · +10 Hull · +15⚔️ Combat",
  },
  {
    key: "fart_cloud_frigate",
    name: "Fart Cloud Frigate",
    emoji: "💨",
    colour: "#66dd00",
    lore: "Deploys methane clouds that confuse enemies and fertilise Nugget growth.",
    archetype: "Support",
    nuggetBonus: 100,
    hullBonus: 25,
    combatBonus: 0,
    crewCapBonus: 2,
    startingBonus: "+100💎 Nuggets · +25 Hull · +2👾 Crew Cap",
  },
  {
    key: "brown_dwarf_battleship",
    name: "Brown Dwarf Battleship",
    emoji: "⚔️",
    colour: "#cc1133",
    lore: "Dense as a collapsed star. One shot from its turd cannon ends debates.",
    archetype: "Brawler",
    nuggetBonus: 30,
    hullBonus: 20,
    combatBonus: 30,
    crewCapBonus: 0,
    startingBonus: "+30💎 Nuggets · +20 Hull · +30⚔️ Combat",
  },
  {
    key: "poop_deck_galleon",
    name: "Poop Deck Galleon",
    emoji: "⚓",
    colour: "#4466cc",
    lore: "A classic retrofitted for deep-space turd exploration. Never sinks.",
    archetype: "Balanced",
    nuggetBonus: 60,
    hullBonus: 30,
    combatBonus: 5,
    crewCapBonus: 1,
    startingBonus: "+60💎 Nuggets · +30 Hull · +5⚔️ Combat · +1👾 Crew Cap",
  },
  {
    key: "cosmic_turd",
    name: "Cosmic Turd",
    emoji: "🌌",
    colour: "#cc44ff",
    lore: "Shaped literally like a turd. Nobody laughs after the first encounter.",
    archetype: "Wild",
    nuggetBonus: 50,
    hullBonus: 50,
    combatBonus: 10,
    crewCapBonus: 1,
    startingBonus: "+50💎 Nuggets · +50 Hull · +10⚔️ Combat · +1👾 Crew Cap",
  },
  {
    key: "golden_nugget",
    name: "Golden Nugget",
    emoji: "✨",
    colour: "#ffcc00",
    lore: "Gilded from bow to stern. Expensive to run. Worth every Nugget.",
    archetype: "Prestige",
    nuggetBonus: 100,
    hullBonus: 40,
    combatBonus: 10,
    crewCapBonus: 1,
    startingBonus: "+100💎 Nuggets · +40 Hull · +10⚔️ Combat · +1👾 Crew Cap",
  },
];

export const SHIP_CLASS_MAP = new Map(SHIP_CLASSES.map(c => [c.key, c]));

export function getShipClass(key: string | null | undefined): ShipClass | undefined {
  if (!key) return undefined;
  return SHIP_CLASS_MAP.get(key);
}
